export const CHANGE_VIEW = "CHANGE_VIEW";

export const REGISTER_SIGNIN = "REGISTER_SIGNIN";

export const REGISTER_SIGNUP = "REGISTER_SIGNUP";

export const VERIFY_USER = "VERIFY_USER";

export const REGISTER_LOGOUT = "REGISTER_LOGOUT";

export const ERROR_STATE = "ERROR_STATE";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const TOGGLE_SESSIONSTORED = "TOGGLE_SESSIONSTORED";
